ALIASES = {
    "NIGERIAN EXCHANGE GROUP PLC": "NGXGROUP",
    "GUARANTY TRUST HOLDING COMPANY PLC": "GTCO",
    "MTN NIGERIA COMMUNICATIONS PLC": "MTNN",
    "SEPLAT ENERGY PLC": "SEPLAT",
    "P Z CUSSONS NIGERIA PLC": "PZ",
    "PZ CUSSONS NIGERIA PLC": "PZ",
    "SUNU ASSURANCES NIGERIA PLC": "SUNUASSUR",
    "ACCESS HOLDINGS PLC": "ACCESSCORP",
    "CUTIX PLC": "CUTIX",
    "PRESCO PLC": "PRESCO",
    "AIRTEL AFRICA PLC": "AIRTELAFRI",
    "JAPAUL GOLD AND VENTURES PLC": "JAPAULGOLD",
    "UNIVERSAL INSURANCE PLC": "UNIVINSURE",
    "CUSTODIAN INVESTMENT PLC": "CUSTODIAN",
    "VFD GROUP PLC": "VFDGROUP",
    "UNIVERSITY PRESS PLC": "UPL",
    "THE INITIATES PLC": "TIP",
    "ABBEY MORTGAGE BANK PLC": "ABBEYBDS",
    "ABBEY BANK PLC": "ABBEYBDS",
    "UAC OF NIGERIA PLC": "UACN",
    "STANBIC IBTC HOLDINGS PLC": "STANBIC",
    "BUA FOODS PLC": "BUAFOODS",
    "AIICO INSURANCE PLC": "AIICO",
    "FCMB GROUP PLC": "FCMB",
    "CORNERSTONE INSURANCE PLC": "CORNERST",
    "CHEMICAL AND ALLIED PRODUCTS PLC": "CAP",
    "DANGOTE CEMENT PLC": "DANGCEM",
    "UNILEVER NIGERIA PLC": "UNILEVER",
    "GUINNESS NIGERIA PLC": "GUINNESS",
    "GUINNESS NIG PLC": "GUINNESS",
    "UNITED CAPITAL PLC": "UCAP",
    "ARADEL HOLDINGS PLC": "ARADEL",
    "MTN NIGERIA": "MTNN",
    "NIDF": "NIDF",
    "NIGERIA INFRASTRUCTURE DEBT FUND": "NIDF",
    "OKOMU": "OKOMUOIL",
    "OKOMU OIL PALM PLC": "OKOMUOIL",
    "LEARN AFRICA PLC": "LEARNAFRCA",
    "ACADEMY PRESS PLC": "ACADEMY",
    # Patch 34: ETF tickers missing from previous runs
    "SIAML PENSION ETF 40": "SIAML40ETF",
    "SIAML ETF 40": "SIAML40ETF",
    "STANBIC IBTC ETF 30": "STANBICETF30",
    "STANBIC IBTC NIGERIA ETF 30": "STANBICETF30",
    # Additional common aliases
    "HONEYWELL FLOUR MILL PLC": "HONYFLOUR",
    "HONEYWELL FLOUR MILLS PLC": "HONYFLOUR",
    "RED STAR EXPRESS PLC": "REDSTAREX",
    "IKEJA HOTEL PLC": "IKEJAHOTEL",
    "AFRICA PRUDENTIAL PLC": "AFRIPRUD",
    "AFRICA PRUDENTIAL REGISTRARS PLC": "AFRIPRUD",
    "ZENITH BANK PLC": "ZENITHBANK",
    "UNITED BANK FOR AFRICA PLC": "UBA",
    "FIDELITY BANK PLC": "FIDELITYBK",
    "FIRST HOLDCO PLC": "FIRSTHOLDCO",
    "FBN HOLDINGS PLC": "FBNH",
    "DANGOTE SUGAR REFINERY PLC": "DANGSUGAR",
    "BUA CEMENT PLC": "BUACEMENT",
    "NESTLE NIGERIA PLC": "NESTLE",
    "NIGERIAN BREWERIES PLC": "NB",
    "LAFARGE AFRICA PLC": "WAPCO",
    "TRANSCORP PLC": "TRANSCORP",
    "TRANSCORP HOTELS PLC": "TRANSCOHOT",
    "TOTALENERGIES MARKETING NIGERIA PLC": "TOTAL",
    "CHAPEL HILL DENHAM": "NIDF",
}

def normalize(value: str) -> str:
    return " ".join(
        value.upper()
        .replace(".", " ")
        .replace(",", " ")
        .replace("-", " ")
        .split()
    )

def resolve_ticker(company: str, title: str = "") -> str:
    hay = normalize(f"{company} {title}")
    for name, ticker in sorted(ALIASES.items(), key=lambda kv: len(kv[0]), reverse=True):
        if normalize(name) in hay:
            return ticker
    return ""
